image: python:3.6

variables:
  WHEEL_DIR: "$CI_PROJECT_DIR/generated_wheels"

Build Wheel:
  script:
    - pip install -r requirements.txt
    - pip wheel --wheel-dir $WHEEL_DIR . --no-deps
  artifacts:
    name: "$CI_BUILD_REF_NAME"
    # 6 months
    expire_in: 6 mos
    paths:
      - $WHEEL_DIR

