name: thumbtack-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install apt dependencies
        run: sudo apt update && sudo apt-get install afflib-tools archivemount avfs cryptsetup disktype exfat-fuse exfat-utils libguestfs-tools libvshadow-utils lvm2 mdadm mtd-utils ocfs2-tools open-vm-tools qemu-utils sleuthkit sqlite3 squashfs-tools vmfs-tools xfsprogs xmount zlib1g-dev
      - name: pip install
        run: pip install -r requirements.txt && pip install -e .
      - name: Download test images
        run: python download-test-images.py --dftt
        working-directory: tests/
      - name: Run tests
        run: pytest
        working-directory: tests/
      - name: Build wheel
        run: pip install wheel && python setup.py sdist bdist_wheel
      - name: Get version/tag from GITHUB_REF
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION  }}
          draft: false
          prerelease: false
      - name: Upload release zip
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/thumbtack-${{ env.RELEASE_VERSION  }}.tar.gz
          asset_name: thumbtack-${{ env.RELEASE_VERSION  }}.tar.gz
          asset_content_type: application/x-tar
      - name: Upload release wheel
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/thumbtack-${{ env.RELEASE_VERSION  }}-py2.py3-none-any.whl
          asset_name: thumbtack-${{ env.RELEASE_VERSION  }}-py2.py3-none-any.whl
      - name: Push to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: "m8YipMgALvXeSVChDKZVH0zJZaTqzqZMZMASFu7Ha+TcSy3oBi2ueq3CcwXPT50/zPsiaDQWwHKt83LwMbWEqALzb460tMfYAJiK1a165KVpeajOT2u9XqxtyJjkblp8S6v7g2y3Fap6dfcEJoR6H9XDZS4UraoDUG3AeRQ6Uu+3nUT1P9sYflKd4aj23arAsQsdrAORpbP9FWUekwlPORLdHJPTX+4l3B7yo+NxRXCqQsfmlj08eRdJRugek//3/ihEa+yuW0O2uRYNvY2jPN+fFF4fTZbqO/O28B4TL5iQFRsP8rbrtm9U0nWDuHbAJ6NVJSIIGV2Dy6jRrbmHr0+zGIKB18bC9mU39vDpeaK9YSKZQ4eBTGIQRTMUJ0S6+330hLcuzKL597gaDy3nY6/BHfCWr7nqbCReo53KoDRLkG1Rfhh6sAh43R3G1A2B7mHY12bfgrQruCXf1PWj3ZXQumEXOfIdaZaWsAYjX0zVnKRkRtp/+FGrFURHzv0WYWLjjAeHPkAEWjVZiHVFSxKjxHDClhpV69qKd8VQnBkJrkS42+Sj2abWI8PhfVjNnevgawSZm7rveTy4VI/vsWTmrTGZdnGrspkf9CYlTw3LkLzMUkaADyIg8US03iJFfAKnRN9YF5qPxbW/3b64WskYaOgstlYaPSY4xL6MFng="

